/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Model.bean.Animal;
import Model.dao.AnimalDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SAMSUNG
 */
public class AnimalCRUD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AnimalCRUD.class.getName());

    // Inicia o UI
    public AnimalCRUD() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        lst_Animal.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();

    }
    
    // Função usada para puxar os dados do Banco de Dados para a tabela, como um SELECT * FROM
     public void readJTable() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO adao = new AnimalDAO();
        
        for(Animal a: adao.readAnimal()) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
    
}
     
     // Usado ao buscar um ID 
     public void searchId(String id) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO adao = new AnimalDAO();
        
        for(Animal a: adao.searchAnimalId(id)) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
    
}
     
     // Usado ao buscar um nome
     public void searchNome(String nome) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO edao = new AnimalDAO();
        
        for(Animal a: edao.searchAnimalNome(nome)) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
     }
     
     //Usado para buscar um sexo
     public void searchSexo(String sexo) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO adao = new AnimalDAO();
        
        for(Animal a: adao.searchAnimalSexo(sexo)) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
    
}
     
     // Usado ao buscar um ID de Espécie
     public void searchEspecie(String especie) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO adao = new AnimalDAO();
        
        for(Animal a: adao.searchAnimalEspecie(especie)) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
    
}
     
     // Usado ao buscar um ID de Espécie
     public void searchCercado(String cercado) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Animal.getModel();
        modelo.setNumRows(0);
        AnimalDAO adao = new AnimalDAO();
        
        for(Animal a: adao.searchAnimalCercado(cercado)) {
            
            modelo.addRow(new Object[]{
                a.getId_animal(),
                a.getNm_animal(),
                a.getDs_sexo(),
                a.getId_especie(),
                a.getId_cercado()
            });
            
        }
    
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_BuscarNome1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Animal = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_AnimalNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_AnimalSexo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_AnimalEspecie = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_AnimalCercado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Buscar = new javax.swing.JTextField();
        btn_BuscarID = new javax.swing.JButton();
        btn_BuscarNome = new javax.swing.JButton();
        btn_BuscarSexo = new javax.swing.JButton();
        btn_BusarEspecie = new javax.swing.JButton();
        btn_BusarCercado = new javax.swing.JButton();
        btn_VerTudo = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();
        btn_Especies = new javax.swing.JButton();
        btn_Cercados = new javax.swing.JButton();
        btn_CriarAnimal = new javax.swing.JButton();
        btn_AtualizarAnimal = new javax.swing.JButton();
        btn_DeletarAnimal = new javax.swing.JButton();

        btn_BuscarNome1.setText("Buscar por Nome");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setText("ANIMAIS");

        jScrollPane1.setForeground(new java.awt.Color(47, 79, 79));

        lst_Animal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lst_Animal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_animal", "nm_animal", "ds_sexo", "id_especie", "id_cercado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lst_Animal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_AnimalMouseClicked(evt);
            }
        });
        lst_Animal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lst_AnimalKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lst_Animal);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 79, 79));
        jLabel2.setText("NOME:");

        txt_AnimalNome.setForeground(new java.awt.Color(47, 79, 79));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 79, 79));
        jLabel3.setText("SEXO:");

        txt_AnimalSexo.setForeground(new java.awt.Color(47, 79, 79));
        txt_AnimalSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AnimalSexoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 79, 79));
        jLabel4.setText("ID DA ESPÉCIE:");

        txt_AnimalEspecie.setForeground(new java.awt.Color(47, 79, 79));
        txt_AnimalEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AnimalEspecieActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(47, 79, 79));
        jLabel5.setText("ID DO CERCADO:");

        txt_AnimalCercado.setForeground(new java.awt.Color(47, 79, 79));
        txt_AnimalCercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_AnimalCercadoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(47, 79, 79));
        jLabel6.setText("BUSCAR:");

        txt_Buscar.setForeground(new java.awt.Color(47, 79, 79));
        txt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarActionPerformed(evt);
            }
        });

        btn_BuscarID.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarID.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarID.setText("BUSCAR POR ID");
        btn_BuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarIDActionPerformed(evt);
            }
        });

        btn_BuscarNome.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarNome.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarNome.setText("BUSCAR POR NOME");
        btn_BuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarNomeActionPerformed(evt);
            }
        });

        btn_BuscarSexo.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarSexo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarSexo.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarSexo.setText("BUSCAR POR GÊNERO");
        btn_BuscarSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarSexoActionPerformed(evt);
            }
        });

        btn_BusarEspecie.setBackground(new java.awt.Color(246, 246, 246));
        btn_BusarEspecie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BusarEspecie.setForeground(new java.awt.Color(47, 79, 79));
        btn_BusarEspecie.setText("BUSCAR PO ID DA ESPÉCIE");
        btn_BusarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BusarEspecieActionPerformed(evt);
            }
        });

        btn_BusarCercado.setBackground(new java.awt.Color(246, 246, 246));
        btn_BusarCercado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BusarCercado.setForeground(new java.awt.Color(47, 79, 79));
        btn_BusarCercado.setText("BUSCAR POR ID DO CERCADO");
        btn_BusarCercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BusarCercadoActionPerformed(evt);
            }
        });

        btn_VerTudo.setBackground(new java.awt.Color(246, 246, 246));
        btn_VerTudo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_VerTudo.setForeground(new java.awt.Color(47, 79, 79));
        btn_VerTudo.setText("VER TUDO");
        btn_VerTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerTudoActionPerformed(evt);
            }
        });

        btn_Voltar.setBackground(new java.awt.Color(246, 246, 246));
        btn_Voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(47, 79, 79));
        btn_Voltar.setText("VOLTAR AO MENU");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_Especies.setBackground(new java.awt.Color(246, 246, 246));
        btn_Especies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Especies.setForeground(new java.awt.Color(47, 79, 79));
        btn_Especies.setText("IR PARA ESPÉCIES");
        btn_Especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EspeciesActionPerformed(evt);
            }
        });

        btn_Cercados.setBackground(new java.awt.Color(246, 246, 246));
        btn_Cercados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cercados.setForeground(new java.awt.Color(47, 79, 79));
        btn_Cercados.setText("IR PARA CERCADOS");
        btn_Cercados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CercadosActionPerformed(evt);
            }
        });

        btn_CriarAnimal.setBackground(new java.awt.Color(246, 246, 246));
        btn_CriarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CriarAnimal.setForeground(new java.awt.Color(47, 79, 79));
        btn_CriarAnimal.setText("CRIAR");
        btn_CriarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarAnimalActionPerformed(evt);
            }
        });

        btn_AtualizarAnimal.setBackground(new java.awt.Color(246, 246, 246));
        btn_AtualizarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_AtualizarAnimal.setForeground(new java.awt.Color(47, 79, 79));
        btn_AtualizarAnimal.setText("ATUALIZAR");
        btn_AtualizarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarAnimalActionPerformed(evt);
            }
        });

        btn_DeletarAnimal.setBackground(new java.awt.Color(246, 246, 246));
        btn_DeletarAnimal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DeletarAnimal.setForeground(new java.awt.Color(47, 79, 79));
        btn_DeletarAnimal.setText("DELETAR");
        btn_DeletarAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_BusarCercado)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_VerTudo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_Cercados)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_Voltar)
                                        .addGap(6, 6, 6))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_BuscarSexo)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(btn_BuscarID)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_BusarEspecie)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(btn_BuscarNome)
                                                .addGap(12, 12, 12))))
                                    .addComponent(txt_Buscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_AnimalSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_AnimalNome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_AnimalEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_AnimalCercado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addComponent(btn_CriarAnimal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_AtualizarAnimal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_DeletarAnimal))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(btn_Especies)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_AnimalNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_AnimalEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_AnimalSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txt_AnimalCercado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_CriarAnimal)
                            .addComponent(btn_AtualizarAnimal)
                            .addComponent(btn_DeletarAnimal))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_BuscarID)
                            .addComponent(btn_BuscarNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_BuscarSexo)
                            .addComponent(btn_BusarEspecie))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_BusarCercado)
                            .addComponent(btn_VerTudo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(btn_Especies)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Cercados)
                            .addComponent(btn_Voltar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_AnimalSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AnimalSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AnimalSexoActionPerformed

    private void txt_AnimalEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AnimalEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AnimalEspecieActionPerformed

    private void txt_AnimalCercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_AnimalCercadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_AnimalCercadoActionPerformed

    private void txt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    // Cria um novo dado
    private void btn_CriarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarAnimalActionPerformed
        Animal a = new Animal();
        AnimalDAO dao = new AnimalDAO();
        
        a.setNm_animal(txt_AnimalNome.getText());
        a.setDs_sexo(txt_AnimalSexo.getText());
        a.setId_especie(Integer.parseInt(txt_AnimalEspecie.getText()));
        a.setId_cercado(Integer.parseInt(txt_AnimalCercado.getText()));
        dao.createAnimal(a);
        
        txt_AnimalNome.setText("");
        txt_AnimalSexo.setText("");
        txt_AnimalEspecie.setText("");
        txt_AnimalCercado.setText("");
        
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CriarAnimalActionPerformed

    private void btn_BuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarIDActionPerformed
        try {
            searchId(txt_Buscar.getText());
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarIDActionPerformed

    private void btn_BuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarNomeActionPerformed
        try {
            searchNome(txt_Buscar.getText());
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarNomeActionPerformed

    private void btn_BuscarSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarSexoActionPerformed
        try {
            searchSexo(txt_Buscar.getText());
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarSexoActionPerformed

    private void btn_BusarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BusarEspecieActionPerformed
        try {
            searchEspecie(txt_Buscar.getText());
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BusarEspecieActionPerformed

    private void btn_BusarCercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BusarCercadoActionPerformed
        try {
            searchCercado(txt_Buscar.getText());
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BusarCercadoActionPerformed

    private void btn_VerTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerTudoActionPerformed
        try {
            readJTable();
        } catch (SQLException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_VerTudoActionPerformed

    // // Seleciona um item da tabela com um clique do mouse
    private void lst_AnimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_AnimalMouseClicked
        
        if(lst_Animal.getSelectedRow() != -1) {
            
            txt_AnimalNome.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 1).toString());
            txt_AnimalSexo.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 2).toString());
            txt_AnimalEspecie.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 3).toString());
            txt_AnimalCercado.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_lst_AnimalMouseClicked

    // Seleciona um item da tabela com as setas do teclado
    private void lst_AnimalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lst_AnimalKeyReleased
        
        if(lst_Animal.getSelectedRow() != -1) {
            
            txt_AnimalNome.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 1).toString());
            txt_AnimalSexo.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 2).toString());
            txt_AnimalEspecie.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 3).toString());
            txt_AnimalCercado.setText(lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 4).toString());
        }
    }//GEN-LAST:event_lst_AnimalKeyReleased

    // Atualiza um dado
    private void btn_AtualizarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarAnimalActionPerformed
        if (lst_Animal.getSelectedRow() != -1) {
            
            Animal a = new Animal();
            AnimalDAO dao = new AnimalDAO();

            a.setId_animal((int)lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 0));
            a.setNm_animal(txt_AnimalNome.getText());
            a.setDs_sexo(txt_AnimalSexo.getText());
            a.setId_especie(Integer.parseInt(txt_AnimalEspecie.getText()));
            a.setId_cercado(Integer.parseInt(txt_AnimalCercado.getText()));
            dao.updateAnimal(a);

            txt_AnimalNome.setText("");
            txt_AnimalSexo.setText("");
            txt_AnimalEspecie.setText("");
            txt_AnimalCercado.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
    }//GEN-LAST:event_btn_AtualizarAnimalActionPerformed

    // Deleta um dado
    private void btn_DeletarAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarAnimalActionPerformed
         if (lst_Animal.getSelectedRow() != -1) {
            
            Animal a = new Animal();
            AnimalDAO dao = new AnimalDAO();

            a.setId_animal((int)lst_Animal.getValueAt(lst_Animal.getSelectedRow(), 0));
            dao.deleteAnimal(a);

            txt_AnimalNome.setText("");
            txt_AnimalSexo.setText("");
            txt_AnimalEspecie.setText("");
            txt_AnimalCercado.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
    }//GEN-LAST:event_btn_DeletarAnimalActionPerformed

    // vai para a tabela de cercados
    private void btn_CercadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CercadosActionPerformed
        try {
            CercadoCRUD c = new CercadoCRUD();
            c.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_CercadosActionPerformed

    // vai para a tabela de espécies
    private void btn_EspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EspeciesActionPerformed
        try {
            EspecieCRUD e = new EspecieCRUD();
            e.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EspeciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AnimalCRUD().setVisible(true);
            } catch (SQLException ex) {
                logger.log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AtualizarAnimal;
    private javax.swing.JButton btn_BusarCercado;
    private javax.swing.JButton btn_BusarEspecie;
    private javax.swing.JButton btn_BuscarID;
    private javax.swing.JButton btn_BuscarNome;
    private javax.swing.JButton btn_BuscarNome1;
    private javax.swing.JButton btn_BuscarSexo;
    private javax.swing.JButton btn_Cercados;
    private javax.swing.JButton btn_CriarAnimal;
    private javax.swing.JButton btn_DeletarAnimal;
    private javax.swing.JButton btn_Especies;
    private javax.swing.JButton btn_VerTudo;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable lst_Animal;
    private javax.swing.JTextField txt_AnimalCercado;
    private javax.swing.JTextField txt_AnimalEspecie;
    private javax.swing.JTextField txt_AnimalNome;
    private javax.swing.JTextField txt_AnimalSexo;
    private javax.swing.JTextField txt_Buscar;
    // End of variables declaration//GEN-END:variables
}
