/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

import Model.bean.Cercado;
import Model.dao.CercadoDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author SAMSUNG
 */
public class CercadoCRUD extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CercadoCRUD.class.getName());

    // Inicia o UI
    public CercadoCRUD() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) lst_Cercado.getModel();
        lst_Cercado.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    // Função usada para puxar os dados do Banco de Dados para a tabela, como um SELECT * FROM
     public void readJTable() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Cercado.getModel();
        modelo.setNumRows(0);
        CercadoDAO cdao = new CercadoDAO();
        
        for(Cercado c: cdao.readCercado()) {
            
            modelo.addRow(new Object[]{
                c.getId_cercado(),
                c.getNm_cercado(),
                c.getDs_tipo(),
            });
            
        }
    
}
     // Usado ao buscar um ID
     public void searchId(String id) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Cercado.getModel();
        modelo.setNumRows(0);
        CercadoDAO cdao = new CercadoDAO();
        
        for(Cercado c: cdao.searchCercadoID(id)) {
            
            modelo.addRow(new Object[]{
                c.getId_cercado(),
                c.getNm_cercado(),
                c.getDs_tipo(),
            });
            
        }
    
}
     
     // Usado ao buscar um nome
     public void searchNome(String nome) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Cercado.getModel();
        modelo.setNumRows(0);
        CercadoDAO cdao = new CercadoDAO();
        
        for(Cercado c: cdao.searchCercadoNome(nome)) {
            
            modelo.addRow(new Object[]{
                c.getId_cercado(),
                c.getNm_cercado(),
                c.getDs_tipo(),
            });
            
        }
    
}
     
     // Usado ao buscar um tipo
     public void searchTipo(String tipo) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Cercado.getModel();
        modelo.setNumRows(0);
        CercadoDAO cdao = new CercadoDAO();
        
        for(Cercado c: cdao.searchCercadoTipo(tipo)) {
            
            modelo.addRow(new Object[]{
                c.getId_cercado(),
                c.getNm_cercado(),
                c.getDs_tipo(),
            });
            
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_Cercado = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_CercadoNome = new javax.swing.JTextField();
        txt_CercadoTipo = new javax.swing.JTextField();
        txt_Buscar = new javax.swing.JTextField();
        btn_Voltar = new javax.swing.JButton();
        btn_CriarCercado = new javax.swing.JButton();
        btn_AtualizarCercado = new javax.swing.JButton();
        btn_DeletarCercado = new javax.swing.JButton();
        btn_BuscarId = new javax.swing.JButton();
        btn_BuscarNome = new javax.swing.JButton();
        btn_BuscarTipo = new javax.swing.JButton();
        btn_VerTudo = new javax.swing.JButton();
        btn_Animais = new javax.swing.JButton();
        btn_Especies = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setText("CERCADOS");

        jScrollPane2.setForeground(new java.awt.Color(47, 79, 79));

        lst_Cercado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lst_Cercado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cercado", "nm_cercado", "ds_tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lst_Cercado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_CercadoMouseClicked(evt);
            }
        });
        lst_Cercado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lst_CercadoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(lst_Cercado);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 79, 79));
        jLabel2.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 79, 79));
        jLabel3.setText("TIPO:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 79, 79));
        jLabel4.setText("BUSCAR:");

        txt_CercadoNome.setForeground(new java.awt.Color(47, 79, 79));
        txt_CercadoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CercadoNomeActionPerformed(evt);
            }
        });

        txt_CercadoTipo.setForeground(new java.awt.Color(47, 79, 79));
        txt_CercadoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CercadoTipoActionPerformed(evt);
            }
        });

        txt_Buscar.setForeground(new java.awt.Color(47, 79, 79));
        txt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BuscarActionPerformed(evt);
            }
        });

        btn_Voltar.setBackground(new java.awt.Color(246, 246, 246));
        btn_Voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(47, 79, 79));
        btn_Voltar.setText("VOLTAR  AO MENU");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_CriarCercado.setBackground(new java.awt.Color(246, 246, 246));
        btn_CriarCercado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CriarCercado.setForeground(new java.awt.Color(47, 79, 79));
        btn_CriarCercado.setText("CRIAR");
        btn_CriarCercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarCercadoActionPerformed(evt);
            }
        });

        btn_AtualizarCercado.setBackground(new java.awt.Color(246, 246, 246));
        btn_AtualizarCercado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_AtualizarCercado.setForeground(new java.awt.Color(47, 79, 79));
        btn_AtualizarCercado.setText("ATUALIZAR");
        btn_AtualizarCercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarCercadoActionPerformed(evt);
            }
        });

        btn_DeletarCercado.setBackground(new java.awt.Color(246, 246, 246));
        btn_DeletarCercado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DeletarCercado.setForeground(new java.awt.Color(47, 79, 79));
        btn_DeletarCercado.setText("DELETAR");
        btn_DeletarCercado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarCercadoActionPerformed(evt);
            }
        });

        btn_BuscarId.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarId.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarId.setText("BUSCAR POR ID");
        btn_BuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarIdActionPerformed(evt);
            }
        });

        btn_BuscarNome.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarNome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarNome.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarNome.setText("BUSCAR POR NOME");
        btn_BuscarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarNomeActionPerformed(evt);
            }
        });

        btn_BuscarTipo.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarTipo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarTipo.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarTipo.setText("BUSCAR POR TIPO");
        btn_BuscarTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarTipoActionPerformed(evt);
            }
        });

        btn_VerTudo.setBackground(new java.awt.Color(246, 246, 246));
        btn_VerTudo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_VerTudo.setForeground(new java.awt.Color(47, 79, 79));
        btn_VerTudo.setText("VER TUDO");
        btn_VerTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerTudoActionPerformed(evt);
            }
        });

        btn_Animais.setBackground(new java.awt.Color(246, 246, 246));
        btn_Animais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Animais.setForeground(new java.awt.Color(47, 79, 79));
        btn_Animais.setText("IR PARA ANIMAIS");
        btn_Animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnimaisActionPerformed(evt);
            }
        });

        btn_Especies.setBackground(new java.awt.Color(246, 246, 246));
        btn_Especies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Especies.setForeground(new java.awt.Color(47, 79, 79));
        btn_Especies.setText("IR PARA ESPÉCIES");
        btn_Especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EspeciesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btn_Especies)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(btn_Voltar))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_CercadoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_CercadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(btn_CriarCercado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_AtualizarCercado)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_DeletarCercado)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btn_Animais)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Buscar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_BuscarId)
                                .addGap(18, 18, 18)
                                .addComponent(btn_BuscarNome))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(btn_BuscarTipo))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(btn_VerTudo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txt_CercadoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_CercadoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CriarCercado)
                    .addComponent(btn_AtualizarCercado)
                    .addComponent(btn_DeletarCercado))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BuscarId)
                    .addComponent(btn_BuscarNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BuscarTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_VerTudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(btn_Animais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Especies)
                    .addComponent(btn_Voltar))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_CercadoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CercadoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CercadoNomeActionPerformed

    private void txt_CercadoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CercadoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CercadoTipoActionPerformed

    private void txt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BuscarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    // Busca um ID
    private void btn_BuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarIdActionPerformed
        try {
            searchId(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarIdActionPerformed

    // Busca um nome
    private void btn_BuscarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarNomeActionPerformed
        try {
            searchNome(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarNomeActionPerformed

    // Busca um tipo
    private void btn_BuscarTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarTipoActionPerformed
        try {
            searchTipo(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarTipoActionPerformed

    // Cria um novo dado
    private void btn_CriarCercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarCercadoActionPerformed
        Cercado c = new Cercado();
        CercadoDAO dao = new CercadoDAO();
        
        c.setNm_cercado(txt_CercadoNome.getText());
        c.setDs_tipo(txt_CercadoTipo.getText());
        dao.createCercado(c);
        
        txt_CercadoNome.setText("");
        txt_CercadoTipo.setText("");
        
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CriarCercadoActionPerformed

    // Busca todos os dados
    private void btn_VerTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerTudoActionPerformed
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_VerTudoActionPerformed

    // Deleta um dado
    private void btn_DeletarCercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarCercadoActionPerformed
       if (lst_Cercado.getSelectedRow() != -1) {
            
            Cercado c = new Cercado();
            CercadoDAO dao = new CercadoDAO();

            c.setId_cercado((int)lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 0));
            dao.updateCercado(c);

            txt_CercadoNome.setText("");
            txt_CercadoTipo.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
    }//GEN-LAST:event_btn_DeletarCercadoActionPerformed

    // Atualiza um dado
    private void btn_AtualizarCercadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarCercadoActionPerformed
        if (lst_Cercado.getSelectedRow() != -1) {
            
            Cercado c = new Cercado();
            CercadoDAO dao = new CercadoDAO();

            c.setId_cercado((int)lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 0));
            c.setNm_cercado(txt_CercadoNome.getText());
            c.setDs_tipo(txt_CercadoTipo.getText());
            dao.updateCercado(c);

            txt_CercadoNome.setText("");
            txt_CercadoTipo.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
    }//GEN-LAST:event_btn_AtualizarCercadoActionPerformed

    // Seleciona um item da tabela com um clique do mouse
    private void lst_CercadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_CercadoMouseClicked
        if(lst_Cercado.getSelectedRow() != -1) {
            
            txt_CercadoNome.setText(lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 1).toString());
            txt_CercadoTipo.setText(lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 2).toString());
            
        }
    }//GEN-LAST:event_lst_CercadoMouseClicked

    // Seleciona um item da tabela com as setas do teclado
    private void lst_CercadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lst_CercadoKeyReleased
        if(lst_Cercado.getSelectedRow() != -1) {
            
            txt_CercadoNome.setText(lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 1).toString());
            txt_CercadoTipo.setText(lst_Cercado.getValueAt(lst_Cercado.getSelectedRow(), 2).toString());
            
        }
    }//GEN-LAST:event_lst_CercadoKeyReleased

    // Vai para o CRUD da tabela de Animais
    private void btn_AnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnimaisActionPerformed
        try {
            AnimalCRUD a = new AnimalCRUD();
            a.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_AnimaisActionPerformed

    // Vai para a tabela de Espécies
    private void btn_EspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EspeciesActionPerformed
        try {
            EspecieCRUD e = new EspecieCRUD();
            e.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EspeciesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new CercadoCRUD().setVisible(true);
            } catch (SQLException ex) {
                logger.log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Animais;
    private javax.swing.JButton btn_AtualizarCercado;
    private javax.swing.JButton btn_BuscarId;
    private javax.swing.JButton btn_BuscarNome;
    private javax.swing.JButton btn_BuscarTipo;
    private javax.swing.JButton btn_CriarCercado;
    private javax.swing.JButton btn_DeletarCercado;
    private javax.swing.JButton btn_Especies;
    private javax.swing.JButton btn_VerTudo;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable lst_Cercado;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_CercadoNome;
    private javax.swing.JTextField txt_CercadoTipo;
    // End of variables declaration//GEN-END:variables
}
