/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Model.bean.Especie;
import Model.dao.EspecieDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ALUNO
 */
public class EspecieCRUD extends javax.swing.JFrame {

    /**
     * Creates new form Especie
     * @throws java.sql.SQLException
     */
    
    // Inicia o UI
    public EspecieCRUD() throws SQLException {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) lst_Especie.getModel();
        lst_Especie.setRowSorter(new TableRowSorter(modelo));
        
        readJTable();
    }
    
    // Função usada para puxar os dados do Banco de Dados para a tabela, como um SELECT * FROM
     public void readJTable() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Especie.getModel();
        modelo.setNumRows(0);
        EspecieDAO edao = new EspecieDAO();
        
        for(Especie e: edao.readEspecie()) {
            
            modelo.addRow(new Object[]{
                e.getId_especie(),
                e.getNm_especie(),
                e.getDs_dieta()
            });
            
        }
    
}
       
     // Usado ao buscar um ID 
     public void searchId(String id) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Especie.getModel();
        modelo.setNumRows(0);
        EspecieDAO edao = new EspecieDAO();
        
        for(Especie e: edao.searchEspecieId(id)) {
            
            modelo.addRow(new Object[]{
                e.getId_especie(),
                e.getNm_especie(),
                e.getDs_dieta()
            });
            
        }
    
}
     // Usado ao buscar um nome
     public void searchNome(String nome) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Especie.getModel();
        modelo.setNumRows(0);
        EspecieDAO edao = new EspecieDAO();
        
        for(Especie e: edao.searchEspecieNome(nome)) {
            
            modelo.addRow(new Object[]{
                e.getId_especie(),
                e.getNm_especie(),
                e.getDs_dieta()
            });
            
        }
    
}
        
     //Usado para buscar uma dieta
     public void searchDieta(String dieta) throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) lst_Especie.getModel();
        modelo.setNumRows(0);
        EspecieDAO edao = new EspecieDAO();
        
        for(Especie e: edao.searchEspecieDieta(dieta)) {
            
            modelo.addRow(new Object[]{
                e.getId_especie(),
                e.getNm_especie(),
                e.getDs_dieta()
            });
            
        }
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_CriarEspecie = new javax.swing.JButton();
        btn_AtualizarEspecie = new javax.swing.JButton();
        btn_DeletarEspecie = new javax.swing.JButton();
        btn_BuscarID = new javax.swing.JButton();
        btn_BuscarEspecie = new javax.swing.JButton();
        btn_BuscarDieta = new javax.swing.JButton();
        btn_VerTudo = new javax.swing.JButton();
        txt_NomeEspecie = new javax.swing.JTextField();
        txt_Dieta = new javax.swing.JTextField();
        txt_Buscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_Especie = new javax.swing.JTable();
        btn_Voltar = new javax.swing.JButton();
        btn_Animais = new javax.swing.JButton();
        btn_Cercados = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setText("ESPÉCIES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(47, 79, 79));
        jLabel2.setText("NOME:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(47, 79, 79));
        jLabel3.setText("DIETA:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(47, 79, 79));
        jLabel4.setText("BUSCAR:");

        btn_CriarEspecie.setBackground(new java.awt.Color(246, 246, 246));
        btn_CriarEspecie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CriarEspecie.setForeground(new java.awt.Color(47, 79, 79));
        btn_CriarEspecie.setText("CRIAR");
        btn_CriarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CriarEspecieActionPerformed(evt);
            }
        });

        btn_AtualizarEspecie.setBackground(new java.awt.Color(246, 246, 246));
        btn_AtualizarEspecie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_AtualizarEspecie.setForeground(new java.awt.Color(47, 79, 79));
        btn_AtualizarEspecie.setText("ATUALIZAR");
        btn_AtualizarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarEspecieActionPerformed(evt);
            }
        });

        btn_DeletarEspecie.setBackground(new java.awt.Color(246, 246, 246));
        btn_DeletarEspecie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_DeletarEspecie.setForeground(new java.awt.Color(47, 79, 79));
        btn_DeletarEspecie.setText("DELETAR");
        btn_DeletarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarEspecieActionPerformed(evt);
            }
        });

        btn_BuscarID.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarID.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarID.setText("BUSCAR POR ID");
        btn_BuscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarIDActionPerformed(evt);
            }
        });

        btn_BuscarEspecie.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarEspecie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarEspecie.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarEspecie.setText("BUSCAR POR NOME");
        btn_BuscarEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarEspecieActionPerformed(evt);
            }
        });

        btn_BuscarDieta.setBackground(new java.awt.Color(246, 246, 246));
        btn_BuscarDieta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_BuscarDieta.setForeground(new java.awt.Color(47, 79, 79));
        btn_BuscarDieta.setText("BUSCAR POR DIETA");
        btn_BuscarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BuscarDietaActionPerformed(evt);
            }
        });

        btn_VerTudo.setBackground(new java.awt.Color(246, 246, 246));
        btn_VerTudo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_VerTudo.setForeground(new java.awt.Color(47, 79, 79));
        btn_VerTudo.setText("VER TUDO");
        btn_VerTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VerTudoActionPerformed(evt);
            }
        });

        txt_NomeEspecie.setForeground(new java.awt.Color(47, 79, 79));

        txt_Dieta.setForeground(new java.awt.Color(47, 79, 79));

        txt_Buscar.setForeground(new java.awt.Color(47, 79, 79));

        jScrollPane1.setForeground(new java.awt.Color(47, 79, 79));

        lst_Especie.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lst_Especie.setForeground(new java.awt.Color(47, 79, 79));
        lst_Especie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_especie", "nm_especie", "ds_dieta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lst_Especie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lst_EspecieMouseClicked(evt);
            }
        });
        lst_Especie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lst_EspecieKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(lst_Especie);

        btn_Voltar.setBackground(new java.awt.Color(246, 246, 246));
        btn_Voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Voltar.setForeground(new java.awt.Color(47, 79, 79));
        btn_Voltar.setText("VOLTAR AO MENU");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        btn_Animais.setBackground(new java.awt.Color(246, 246, 246));
        btn_Animais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Animais.setForeground(new java.awt.Color(47, 79, 79));
        btn_Animais.setText("IR PARA ANIMAIS");
        btn_Animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnimaisActionPerformed(evt);
            }
        });

        btn_Cercados.setBackground(new java.awt.Color(246, 246, 246));
        btn_Cercados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cercados.setForeground(new java.awt.Color(47, 79, 79));
        btn_Cercados.setText("IR PARA CERCADOS");
        btn_Cercados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CercadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btn_Cercados)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_Voltar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_NomeEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_Dieta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(btn_CriarEspecie)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_AtualizarEspecie)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_DeletarEspecie))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btn_BuscarID)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_BuscarEspecie))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_BuscarDieta)
                                .addComponent(btn_Animais))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btn_VerTudo)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_NomeEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Dieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_CriarEspecie)
                    .addComponent(btn_AtualizarEspecie)
                    .addComponent(btn_DeletarEspecie))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_BuscarID)
                    .addComponent(btn_BuscarEspecie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_BuscarDieta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_VerTudo)
                .addGap(83, 83, 83)
                .addComponent(btn_Animais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Voltar)
                    .addComponent(btn_Cercados))
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Cria um novo dado
    private void btn_CriarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CriarEspecieActionPerformed
        Especie e = new Especie();
        EspecieDAO dao = new EspecieDAO();
        
        e.setNm_especie(txt_NomeEspecie.getText());
        e.setDs_dieta(txt_Dieta.getText());
        dao.createEspecie(e);
        
        txt_NomeEspecie.setText("");
        txt_Dieta.setText("");
        
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_CriarEspecieActionPerformed

    // Atualiza um dado
    private void btn_AtualizarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarEspecieActionPerformed
        
        if (lst_Especie.getSelectedRow() != -1) {
            
            Especie e = new Especie();
            EspecieDAO dao = new EspecieDAO();

            e.setId_especie((int)lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 0));
            e.setNm_especie(txt_NomeEspecie.getText());
            e.setDs_dieta(txt_Dieta.getText());
            dao.updateEspecie(e);

            txt_NomeEspecie.setText("");
            txt_Dieta.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
        
    }//GEN-LAST:event_btn_AtualizarEspecieActionPerformed

    // Deleta um dado
    private void btn_DeletarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarEspecieActionPerformed
            
        if (lst_Especie.getSelectedRow() != -1) {
            
            Especie e = new Especie();
            EspecieDAO dao = new EspecieDAO();

            e.setId_especie((int)lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 0));
            dao.deleteEspecie(e);

            txt_NomeEspecie.setText("");
            txt_Dieta.setText("");

            try {
                readJTable();
            } catch (SQLException ex) {
                Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Por favor selecione um item da lista com um clique do mouse.");
        }
    }//GEN-LAST:event_btn_DeletarEspecieActionPerformed

    // Busca um dado pelo nome
    private void btn_BuscarEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarEspecieActionPerformed
        try {
            searchNome(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarEspecieActionPerformed

    // Seleciona um item da tabela com um clique do mouse
    private void lst_EspecieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lst_EspecieMouseClicked
        
        if(lst_Especie.getSelectedRow() != -1) {
            
            txt_NomeEspecie.setText(lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 1).toString());
            txt_Dieta.setText(lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 2).toString());
            
        }
        
    }//GEN-LAST:event_lst_EspecieMouseClicked

    // Seleciona um item da tabela com as setas do teclado
    private void lst_EspecieKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lst_EspecieKeyReleased
        if(lst_Especie.getSelectedRow() != -1) {
            
            txt_NomeEspecie.setText(lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 1).toString());
            txt_Dieta.setText(lst_Especie.getValueAt(lst_Especie.getSelectedRow(), 2).toString());
            
        }
    }//GEN-LAST:event_lst_EspecieKeyReleased

    // Busca um dado pela dieta
    private void btn_BuscarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarDietaActionPerformed
        try {
            searchDieta(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarDietaActionPerformed

    // Busca todos os dados
    private void btn_VerTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VerTudoActionPerformed
        try {
            readJTable();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_VerTudoActionPerformed

    // Busca um dado pelo ID
    private void btn_BuscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BuscarIDActionPerformed
        try {
            searchId(txt_Buscar.getText());
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_BuscarIDActionPerformed

    // Volta ao menu
    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    // Vai para o CRUD da tabela de Animais
    private void btn_AnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnimaisActionPerformed
        try {
            AnimalCRUD a = new AnimalCRUD();
            a.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_AnimaisActionPerformed

    // Vai para o CRUD da tabela de Recintos
    private void btn_CercadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CercadosActionPerformed
        try {
            CercadoCRUD c = new CercadoCRUD();
            c.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CercadosActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspecieCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspecieCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspecieCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspecieCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EspecieCRUD().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EspecieCRUD.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Animais;
    private javax.swing.JButton btn_AtualizarEspecie;
    private javax.swing.JButton btn_BuscarDieta;
    private javax.swing.JButton btn_BuscarEspecie;
    private javax.swing.JButton btn_BuscarID;
    private javax.swing.JButton btn_Cercados;
    private javax.swing.JButton btn_CriarEspecie;
    private javax.swing.JButton btn_DeletarEspecie;
    private javax.swing.JButton btn_VerTudo;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable lst_Especie;
    private javax.swing.JTextField txt_Buscar;
    private javax.swing.JTextField txt_Dieta;
    private javax.swing.JTextField txt_NomeEspecie;
    // End of variables declaration//GEN-END:variables
}
