/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main;

/**
 *
 * @author SAMSUNG
 */
public class Guia extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Guia.class.getName());

    /**
     * Creates new form Guia
     */
    public Guia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Animais = new javax.swing.JButton();
        btn_Cercados = new javax.swing.JButton();
        btn_Especies = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_Atr1 = new javax.swing.JLabel();
        btn_VoltarMenu = new javax.swing.JButton();
        lbl_Atr2 = new javax.swing.JLabel();
        lbl_Atr3 = new javax.swing.JLabel();
        lbl_Atr4 = new javax.swing.JLabel();
        lbl_Atr5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_Animais.setBackground(new java.awt.Color(246, 246, 246));
        btn_Animais.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Animais.setForeground(new java.awt.Color(47, 79, 79));
        btn_Animais.setText("ANIMAIS");
        btn_Animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnimaisActionPerformed(evt);
            }
        });

        btn_Cercados.setBackground(new java.awt.Color(246, 246, 246));
        btn_Cercados.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Cercados.setForeground(new java.awt.Color(47, 79, 79));
        btn_Cercados.setText("CERCADOS");
        btn_Cercados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CercadosActionPerformed(evt);
            }
        });

        btn_Especies.setBackground(new java.awt.Color(246, 246, 246));
        btn_Especies.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Especies.setForeground(new java.awt.Color(47, 79, 79));
        btn_Especies.setText("ESPÉCIES");
        btn_Especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EspeciesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setText("GUIA");

        lbl_Atr1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_Atr1.setForeground(new java.awt.Color(47, 79, 79));

        btn_VoltarMenu.setBackground(new java.awt.Color(246, 246, 246));
        btn_VoltarMenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_VoltarMenu.setForeground(new java.awt.Color(47, 79, 79));
        btn_VoltarMenu.setText("VOLTAR AO MENU");
        btn_VoltarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarMenuActionPerformed(evt);
            }
        });

        lbl_Atr2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_Atr2.setForeground(new java.awt.Color(47, 79, 79));

        lbl_Atr3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_Atr3.setForeground(new java.awt.Color(47, 79, 79));

        lbl_Atr4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_Atr4.setForeground(new java.awt.Color(47, 79, 79));

        lbl_Atr5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lbl_Atr5.setForeground(new java.awt.Color(47, 79, 79));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Atr1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_VoltarMenu)
                        .addGap(0, 181, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btn_Animais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Cercados)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Especies))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel1)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addComponent(lbl_Atr4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Atr5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Atr3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_Atr2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Animais)
                    .addComponent(btn_Cercados)
                    .addComponent(btn_Especies))
                .addGap(18, 18, 18)
                .addComponent(lbl_Atr1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Atr2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Atr3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Atr4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_Atr5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btn_VoltarMenu)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnimaisActionPerformed
        lbl_Atr1.setText(" id_animal - O identificador único.");
        lbl_Atr2.setText(" nm_animal - O nome do animal específico.");
        lbl_Atr3.setText(" ds_sexo - Se o animal é macho, fêmea ou outro.");
        lbl_Atr4.setText(" id_especie - Qual a espécie do animal?");
        lbl_Atr5.setText(" id_cercado - Em qual cercado esse animal fica?");
    }//GEN-LAST:event_btn_AnimaisActionPerformed

    private void btn_CercadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CercadosActionPerformed
        lbl_Atr1.setText(" id_cercado - O identificador único.");
        lbl_Atr2.setText(" nm_cercado - O nome do cercado.");
        lbl_Atr3.setText(" ds_tipo - O tipo de cercado.");
        lbl_Atr4.setText(" -- Externo, Interno, Terrário, Lago etc..");
        lbl_Atr5.setText("");
    }//GEN-LAST:event_btn_CercadosActionPerformed

    private void btn_EspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EspeciesActionPerformed
        lbl_Atr1.setText(" id_especie - O identificador único.");
        lbl_Atr2.setText(" nm_especie - O nome da espécie.");
        lbl_Atr3.setText(" ds_dieta - A dieta daquela espécie.");
        lbl_Atr4.setText(" -- Herbívoro, Canívoro, Pscívoro, Onívoro etc.");
        lbl_Atr5.setText("");
    }//GEN-LAST:event_btn_EspeciesActionPerformed

    private void btn_VoltarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarMenuActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_VoltarMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Guia().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Animais;
    private javax.swing.JButton btn_Cercados;
    private javax.swing.JButton btn_Especies;
    private javax.swing.JButton btn_VoltarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Atr1;
    private javax.swing.JLabel lbl_Atr2;
    private javax.swing.JLabel lbl_Atr3;
    private javax.swing.JLabel lbl_Atr4;
    private javax.swing.JLabel lbl_Atr5;
    // End of variables declaration//GEN-END:variables
}
