/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ALUNO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Especies = new javax.swing.JButton();
        btn_Cercados = new javax.swing.JButton();
        btn_Animais = new javax.swing.JButton();
        btn_Sair = new javax.swing.JButton();
        btn_Guia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(47, 79, 79));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ZOO");

        btn_Especies.setBackground(new java.awt.Color(246, 246, 246));
        btn_Especies.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Especies.setForeground(new java.awt.Color(47, 79, 79));
        btn_Especies.setText("ESPÉCIES");
        btn_Especies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EspeciesActionPerformed(evt);
            }
        });

        btn_Cercados.setBackground(new java.awt.Color(246, 246, 246));
        btn_Cercados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Cercados.setForeground(new java.awt.Color(47, 79, 79));
        btn_Cercados.setText("CERCADOS");
        btn_Cercados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CercadosActionPerformed(evt);
            }
        });

        btn_Animais.setBackground(new java.awt.Color(246, 246, 246));
        btn_Animais.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Animais.setForeground(new java.awt.Color(47, 79, 79));
        btn_Animais.setText("ANIMAIS");
        btn_Animais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnimaisActionPerformed(evt);
            }
        });

        btn_Sair.setBackground(new java.awt.Color(246, 246, 246));
        btn_Sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Sair.setForeground(new java.awt.Color(47, 79, 79));
        btn_Sair.setText("SAIR");
        btn_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SairActionPerformed(evt);
            }
        });

        btn_Guia.setBackground(new java.awt.Color(246, 246, 246));
        btn_Guia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Guia.setForeground(new java.awt.Color(47, 79, 79));
        btn_Guia.setText("GUIA");
        btn_Guia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_Cercados)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Especies)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btn_Animais)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Sair)
                    .addComponent(btn_Guia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btn_Animais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Especies)
                    .addComponent(btn_Cercados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_Guia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Sair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Vai para a tabela Cercado
    private void btn_CercadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CercadosActionPerformed
        try {
            CercadoCRUD r = new CercadoCRUD();
            r.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_CercadosActionPerformed

    // Vai para a tabela Especie
    private void btn_EspeciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EspeciesActionPerformed
        try {
            EspecieCRUD e = new EspecieCRUD();
            e.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_EspeciesActionPerformed

    // Fecha o programa
    private void btn_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SairActionPerformed
        dispose();
    }//GEN-LAST:event_btn_SairActionPerformed

    // // Vai para a tabela Animal
    private void btn_AnimaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnimaisActionPerformed
        try {
            AnimalCRUD a = new AnimalCRUD();
            a.setVisible(true);
            dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_AnimaisActionPerformed

    // Vai para o Guia
    private void btn_GuiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuiaActionPerformed
        Guia g = new Guia();
        g.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_GuiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Animais;
    private javax.swing.JButton btn_Cercados;
    private javax.swing.JButton btn_Especies;
    private javax.swing.JButton btn_Guia;
    private javax.swing.JButton btn_Sair;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
